Dev1
Karinka-malinka/GophKeeper pull request #2
Opened 2024-06-19 18:34 UTC by Karinka-malinka

2024-06-25 21:29 UTC, Bazys requested changes
не уж то у тебя никакая кодовая база не повторяется между клиентом и серверолм?. Точно надо их в разных папках держвть?
Может стандартно в cmd две точки входа, в сервер и клиент. а в internal щбщий код если он есть?

proto обычно выносят в корень проекта в папку типа api или docs не важно точно как, но главное что бы было понятно что там можно найти некоторые контракты к сервису.

2024-06-26 08:24 UTC, Karinka-malinka commented
> не уж то у тебя никакая кодовая база не повторяется между клиентом и серверолм?. Точно надо их в разных папках держвть? Может стандартно в cmd две точки входа, в сервер и клиент. а в internal щбщий код если он есть?

не повторяется, только вызов proto. Как правильно, я не знаю, так как не писала ранее клиента и сервера одновременно в одном репозитории. Сделала, как посчитала логичнее и удобнее будет потом читать код (мне, тебе, кому угодно)

> proto обычно выносят в корень проекта в папку типа api или docs не важно точно как, но главное что бы было понятно что там можно найти некоторые контракты к сервису.

вынесла в папку api

2024-06-30 07:48 UTC, Bazys approved these changes
есть несколько вопросов, но они скорее вопросы 3 порядка )))
А так всё отлично!

2024-06-30 07:48 UTC, Bazys commented on server/internal/app/user/auth.go
> +func (ua *Users) TokenAuthMiddlewareGRPS(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
есть готовый пакет от гугла - authz (на будущее)

2024-06-30 07:48 UTC, Bazys commented on server/internal/app/filedata/filedata.go
> +type IFileDataStore interface {
вот эти 3 интерфейса прям так и просятся быть описанными через дженерики. Будет только 1 интерфейс, который принимает тип, с которым работает.

2024-06-30 07:52 UTC, Bazys commented on server/internal/controller/handler/management/bankcard.go
> +	go func() {
а тут точно нужна горутина? или от того что знаешь и умеешь?
ну а если реально надо, посмотри в сторону errgroup - там обработка ошибок из коробки и не надо следить за закрытием каналов.

2024-11-14 06:13 UTC, merged